### ISSUE TITLE
Static method

### ISSUE THREAD

**Issue by IanaKhitsko** [dmmaks/MIPZ_lab1#4]
https://github.com/dmmaks/MIPZ_lab1/blob/333681c39e42167b62dfc6eb906f9685c77f86cf/src/main/java/org/example/Renju.java#L40

Why the method is static? The same for the next method

**Comment by dmmaks** [comment]
Due to the fact these methods are located in the main class and are directly or indirectly called by the public static void main method instead of creating instances of other classes, these methods are required to be static as per the java syntax it is forbidden to call non-static methods of a class from its static method, and main method is obliged to be static. At the same time, for such a program it would be redundant to crate multiple classes, therefore the best solution here is to simply make the mthods static.
